config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'

  resources :lists, only: [ :index, :show, :new, :create, :destroy ] do
    resources :bookmarks, only: [ :new, :create ]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
# before_action :set_bookmark, only: [:destroy]

def new
  @bookmark = Bookmark.new
end


def create
  @bookmark = Bookmark.new(bookmark_params)
  if @bookmark.save
    redirect_to bookmark_path(@bookmark)
  else
    render 'new'
  end
end

# def destroy
# end

# def set_bookmark
# end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

 <%= simple_form_for [@list, @bookmark] do |f| %>
   <%= f.input :comment %>
   <%= f.association :movie, prompt: "select a movie" %>
   <%= f.submit class: 'btn btn-success' %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= image_tag "logo.jpg", alt: "Movies", width: 200, class: 'logo' %>


<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path "background.jpg" %>')" >
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <h1>All lists</h1>
        <ul class="list-group mb-3">
          <% @lists.each do |list| %>
            <li class="list-group-item">
              <%= link_to list.name, list_path(list) %>
            </li>
          <% end %>
        </ul>
        <%= link_to "Add a new list", new_list_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <%= simple_form_for @list do |f| %>
   <%= f.input :name %>
   <%= f.submit "add"%>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1>Your list <%= @list.name%></h1>
  <br>
  <ul class="list-group mb-3">
    <% @movies.each do |movie| %>
      <li class="list-group-item">
      <img src="<%= movie.poster_url %>" width="100px" alt="">
      <%= movie.title %><%= movie.overview %>
      <br>
      Rating: <%= movie.rating %>
      </li>
    <% end %>
  </ul>
  <br>
  <br>
  <%= link_to "Back", lists_path, class: "btn btn-success" %>
   <br>
  <br>
  <%= link_to "Add a bookmark",  new_list_bookmark_path(@list), class: "btn btn-success" %>
</div>